// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzhxfxnlykvnxzczxqks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6aHhmeG5seWt2bnh6Y3p4cWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzM4MDYsImV4cCI6MjA2MTkwOTgwNn0.VgY9Lr9VEC5Qbgu7I-h3CpvJzgJw3Lru_6XjiPcBSQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);